appname = sga_actualizacion_dato_mid
httpport = ${SGA_MID_ACTUALIZACION_DATO_HTTP_PORT}
runmode = ${SGA_MID_ACTUALIZACION_DATO_RUNMODE||prod}
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn =

SolicitudDocenteService = ${SOLICITUD_DOCENTE_SERVICE}
TercerosService= ${TERCEROS_SERVICE}